### ISSUE TITLE
run_ts_web.py的144行ka.kline，无法读取变量

### ISSUE THREAD

**Issue by longshao-mogu** [zengbin93/czsc_web_ui#1]
您好，在run_ts_web.py的144行使用了ka.kline，但是KlineAnalyze中并没有kline变量，只有kline_new和kline_raw变量，而且kline_new中不包含 'fx_mark', 'fx', 'bi', 'xd' 列。本地直接运行会出错，能指导一下应该怎么处理么？

```
ka = KlineAnalyze(kline)
kline = pd.DataFrame(ka.kline)
kline = kline.fillna("")
columns = ["dt", "open", "close", "low", "high", "vol", 'fx_mark', 'fx', 'bi', 'xd']
```

**Comment by zengbin93** [comment]
@longshao-mogu 你好，已经修复了，你pull最新代码。

**Comment by longshao-mogu** [comment]
> @longshao-mogu 你好，已经修复了，你pull最新代码。

非常感谢，已经可以了。
